Models/Contato.cs
using System.ComponentModel.DataAnnotations;

namespace MinhaWebApi.Models
{
    public class Contato
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "O campo <b><i>{0}</i></b> é obrigatório")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "O tamanho do campo <b><i>{0}</i></b> deve estar entre {2} e {1}")]
        [Display(Name = "Nome")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "O campo <b><i>{0}</i></b> é obrigatório")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "O tamanho do campo <b><i>{0}</i></b> deve estar entre {2} e {1}")]
        [Display(Name = "Canal")]
        public string CanalContato { get; set; }

        [Required(ErrorMessage = "O campo <b><i>{0}</i></b> é obrigatório")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "O tamanho do campo <b><i>{0}</i></b> deve estar entre {2} e {1}")]
        [Display(Name = "Observação")]
        public string ObservacaoContato { get; set; }

        [Display(Name = "Tipo Canal")]
        public TipoContato TipoContato { get; set; }

        [Display(Name = "Tipo Canal")]
        public int TipoContatoId { get; set; }

        public Contato()
        {

        }

        public Contato(int id, string nome, TipoContato tipoContato, string canalContato, string observacaoContato)
        {
            Id = id;
            Nome = nome;
            TipoContato = tipoContato;
            CanalContato = canalContato;
            ObservacaoContato = observacaoContato;
        }
    }
}

Models/TipoContato.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MinhaWebApi.Models
{
    public class TipoContato
    {
        public int Id { get; set; }
        public string Descricao { get; set; }

        public TipoContato()
        {

        }

        public TipoContato(string descricao)
        {
            Descricao = descricao;
        }

        public TipoContato(int id, string descricao)
        {
            Id = id;
            Descricao = descricao;
        }
    }
}

Models/ViewModels/ContatoViewModel.cs
using System.Collections.Generic;

namespace MinhaWebApi.Models.ViewModels
{
    public class ContatoViewModel
    {
        public Contato Contato { get; set; }
        public ICollection<TipoContato> TipoContato { get; set; }
    }
}

Models/ViewModels/ErrorViewModel.cs
using System;

namespace MinhaWebApi.Models.ViewModels
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }
        public string Message { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ContatoController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MinhaWebApi.Models;
using MinhaWebApi.Services;
using MinhaWebApi.Models.ViewModels;
using System.Diagnostics;

namespace MinhaWebApi.Controllers
{
    public class ContatoController : Controller
    {
        private readonly MinhaWebApiContext _context;
        private readonly ContatoService _contatoService;
        private readonly TipoContatoService _tipoContatoService;

        public ContatoController(MinhaWebApiContext context, ContatoService contatoService, TipoContatoService tipoContatoService)
        {
            _contatoService = contatoService;
            _tipoContatoService = tipoContatoService;
            _context = context;
        }

        // GET: Contatos
        public async Task<IActionResult> Index()
        {
            var list = await _contatoService.FindAllAsync();
            return View(list);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Id não fornecido" });
            }

            var obj = await _contatoService.FindByIdAsync(id.Value);
            if (obj == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Id não encontrado" });
            }

            return View(obj);
        }

        // GET: Contatos/Create
        public async Task<IActionResult> Create()
        {
            var tipoContato = await _tipoContatoService.FindAllAsync();
            var viewModel = new ContatoViewModel { TipoContato = tipoContato };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Contato contato)
        {
            _contatoService.Insert(contato);
            return RedirectToAction(nameof(Index));
        }

        // GET: Contatos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Id não fornecido" });
            }

            var obj = await _contatoService.FindByIdAsync(id.Value);
            if (obj == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Id não encontrado" });
            }

            List<TipoContato> departments = await _tipoContatoService.FindAllAsync();
            ContatoViewModel viewModel = new ContatoViewModel { Contato = obj, TipoContato = departments };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Contato contato)
        {
            if (id != contato.Id)
            {
                return NotFound();
            }

            try
            {
                _context.Update(contato);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ContatoExists(contato.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Contatos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Id não fornecido" });
            }

            var obj = await _contatoService.FindByIdAsync(id.Value);
            if (obj == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Id não encontrado" });
            }

            return View(obj);
        }

        // POST: Contatos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contato = await _context.Contato.FindAsync(id);
            _context.Contato.Remove(contato);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContatoExists(int id)
        {
            return _context.Contato.Any(e => e.Id == id);
        }

        public IActionResult Error(string message)
        {
            var viewModel = new ErrorViewModel
            {
                Message = message,
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
            };
            return View(viewModel);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MinhaWebApi.Models.ViewModels;

namespace MinhaWebApi.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new MinhaWebApi.Models.ViewModels.ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Contato/Create.cshtml
@model MinhaWebApi.Models.ViewModels.ContatoViewModel

@{
    ViewData["Title"] = "Inclusão de Contato";
}

<h2>@ViewData["Title"]</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Contato.Nome" class="control-label"></label>
                <input asp-for="Contato.Nome" class="form-control" />
                <span asp-validation-for="Contato.Nome" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Contato.TipoContatoId" class="control-label"></label>
                <select asp-for="Contato.TipoContatoId" asp-items="@(new SelectList(Model.TipoContato,"Id",
                "Descricao"))" class="form-control"></select>
            </div>

            <div class="form-group">
                <label asp-for="Contato.CanalContato" class="control-label"></label>
                <input asp-for="Contato.CanalContato" class="form-control" />
                <span asp-validation-for="Contato.CanalContato" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contato.ObservacaoContato" class="control-label"></label>
                <input asp-for="Contato.ObservacaoContato" class="form-control" />
                <span asp-validation-for="Contato.ObservacaoContato" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a asp-action="Index" class="btn btn-warning">Voltar</a> |
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Views/Contato/Delete.cshtml
@model  MinhaWebApi.Models.Contato

@{
    ViewData["Title"] = "Excluir";
}

<h2>@ViewData["Title"]</h2>

<h5>Deseja realmente excluir o contato selecionado?</h5>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoContato)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TipoContato.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CanalContato)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CanalContato)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ObservacaoContato)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ObservacaoContato)
        </dd>
    </dl>
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <a asp-action="Index" class="btn btn-warning">Voltar</a> |
        <input type="submit" value="Excluir" class="btn btn-danger" />
    </form>

</div>

Views/Contato/Details.cshtml
@model MinhaWebApi.Models.Contato
@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
<hr />
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoContato)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TipoContato.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CanalContato)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CanalContato)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ObservacaoContato)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ObservacaoContato)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index" class="btn btn-warning">Voltar</a> |
    <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model.Id">Editar</a>
</div>

Views/Contato/Edit.cshtml
@model MinhaWebApi.Models.ViewModels.ContatoViewModel

@{
    ViewData["Title"] = "Editar";
}

<h2>@ViewData["Title"]</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="Contato.Id" />
            <div class="form-group">
                <label asp-for="Contato.Nome" class="control-label"></label>
                <input asp-for="Contato.Nome" class="form-control" />
                <span asp-validation-for="Contato.Nome" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Contato.TipoContatoId" class="control-label"></label>
                <select asp-for="Contato.TipoContatoId" asp-items="@(new SelectList(Model.TipoContato,"Id",
                "Descricao"))" class="form-control"></select>
            </div>

            <div class="form-group">
                <label asp-for="Contato.CanalContato" class="control-label"></label>
                <input asp-for="Contato.CanalContato" class="form-control" />
                <span asp-validation-for="Contato.CanalContato" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contato.ObservacaoContato" class="control-label"></label>
                <input asp-for="Contato.ObservacaoContato" class="form-control" />
                <span asp-validation-for="Contato.ObservacaoContato" class="text-danger"></span>
            </div>
            <div class="form-group">
                <a asp-action="Index" class="btn btn-warning">Voltar</a> |
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Views/Contato/Index.cshtml
@model IEnumerable<MinhaWebApi.Models.Contato>

@{
    ViewData["Title"] = "Contatos Meta";
}

<h1>@ViewData["Title"]</h1>


<p>
    <a asp-action="Create" class="btn btn-primary btn-lg">Incluir</a>
</p>

<table class="table table-striped table-hover">
    <thead>
        <tr class="success">
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CanalContato)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ObservacaoContato)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CanalContato)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ObservacaoContato)
                </td>
                <td>
                    <a asp-action="Edit" class="btn btn-warning" asp-route-id="@item.Id">Editar</a>
                    <a asp-action="Details" class="btn btn-success" asp-route-id="@item.Id">Detalhar</a>
                    <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.Id">Excluir</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Seja bem vindo!</h1>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MinhaWebApi</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-transparent border-bottom box-shadow mb-3">
            <div class= "p-3 mb-2 bg-transparent text-white container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    Desafio Meta


                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class=" navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <b><a class="nav-link text-justify" asp-area="" asp-controller="Home" asp-action="Index">Home</a></b>
                        </li>
                        <li class="nav-item">
                            <b><a class="nav-link text-justify" asp-area="" asp-controller="Contato" asp-action="Index">Contatos Meta</a></b>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - MinhaWebApi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>